
server:
  port: 8080

spring:
  datasource:
#      name: test
      url: jdbc:mysql://127.0.0.1:3306/stuinformation?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
      mapper-locations: classpath:mapper/*.xml
      type-aliases-package: com.example.demo.entity
swagger:
      enabled: true